### ISSUE TITLE
How to preprocess input text?

### ISSUE THREAD

**Issue by kashimotoxiang** [moonlightlane/QG-Net#3]
I can run the test demo and get good results. But how can I correctly preprocess customized documents to generate questions? I found file `preproc_squad.py`, but the code is used to process training/test data. It's a little hard for me to extract the preprocessing code. Can you provide the input document preprocessing scripts? or simply describe the work procedure？

**Comment by zichaow** [comment]
@kashimotoxiang Hello, unfortunately currently script to processing your own input is not provided. The major difficulty is that the input to QG-Net needs a special token (indicator) that indicates where the answer words are in the input sentence. This is because for a given input sentence, depending on which word or phrase you want to ask a question about, you can potentially generate very different questions. For example, if I ask the question from the sentence "UIUC is located 2 hours away from Chicago." If I want to ask about "UIUC", I would ask the question "Which university is located 2 hours away from Chicago?" If I want to ask about "Chicago", I would ask the question "Which city is located 2 hours away from UIUC?" 

The SQuAD dataset is nice in that it already contains the answer token (indicators) that indicates which word or phrases in the input is the answer. Unfortunately, in other documents, there is not answer tokens. What we did for the OpenStax textbooks is that we use existing parsers to generate a lot of potentially noisy phrases, then manually select the ones that look interesting, and then generate questions from them. 

Because the process involves manually eliminating uninteresting answer word/phrases, we don't think this is mature enough to include in the QG-Net repository. Automating answer token selection/generation is part of our ongoing work. 

That said, if you do want to use QG-Net to generate questions from custom input, here is the processing steps:

1) tokenization using Stanford CoreNLP. This can be done for any text document, as long as the input is the specified format as required by CoreNLP. 

2) Assemble the CoreNLP output into a text document similar to `input.txt` in the path `QG-Net/test/input.for.test/`. The format is, one sentence per line; in each line are space-separated word-feature; each word-feature is in the format of `word|feature1|feature2|feature3|answer-token`. When you process your custom input using CoreNLP, you will get the first three features but not the last one. You will need to manually fill in the last feature for each word in your input. The first three features are: case (upper case or lower case), part of speech tag (POS), and name entity tag (NER). You can easily assemble CoreNLP output to the above format by looping through the CoreNLP output for each feature. You may need to specify CoreNLP output format that allows you to do this easily. 

3) When you have done the above steps, the assembled file which looks like `input.txt` should be ready as input to QG-Net.

I have a script `preproc_os.py` that processes custom input (OpenStax textbooks). In that script, the answer token comes from 2 sources: 1) special NER or POS tags and 2) index table at the end of a textbook. I think it might not be too hard to modify this file for your use; just remove the part that deals with the index table (although you will get a lot of noisy answer tokens because many answer tokens extracted from special NER and POS are very bad, so you might want to manually select the ones that are interesting to actually generated questions from).

Let me know if you have further questions! I'll leave the issue open for now.

**Comment by kashimotoxiang** [comment]
Thank you for your response! Because CoreNLP is too slow, I have completed a preprocessing script to generate `input.txt` based on Spacy like this:
```python
nlp = spacy.load('en')

def process_dataset(data):
    """Iterate processing (tokenize, parse, etc) dataset multithreaded."""

    for idx, line in enumerate(data):
        doc = nlp(line)

        # document tokenizations
        # document = [_convert(x) for x in c_tokens[idx]['words']]
        document = [token.text for token in doc]
        pos = [token.tag_ for token in doc]
        ner = []
        pre_end = 0
        for ent in doc.ents:
            label = _convert(ent.label_)
            ner = ner+(ent.start-pre_end) * ["O"]+[label]*(ent.end-ent.start)
            pre_end = ent.end

        ner = ner+(len(pos)-pre_end) * ["O"]
        yield {
            'document': document,
            'pos': pos,
            'ner': ner
```
But I think this could be not the best way because the tags of CoreNLP and Spacy are different. So there needs some work to convert their tags.

Sometimes people only want to verify the performance by selecting some sentences and observe what output come out. So I think generating `input.txt` and getting the output from QG-Net can be combined into one step. 

Anyway, it is an awesome job. Question Generator is exactly what I am interested in. I think my next step should be reproducing your paper based on Spacy because Spacy is faster and has more features.

**Comment by zichaow** [comment]
@kashimotoxiang Hello, I think as long as the tag is transformed to the same format as those produced by corenlp, it should be fine. Also, when I tried corenlp it was not that slow; perhaps you are working with a corpus much larger than mine... 

And yes, it would be super nice to just have the user provide the input text and the system does all the preprocessing in addition to question generation, and then outputs a question. This corpus only implements the second part, i.e., question generation; we are working on automating the first part (i.e., automatically selecting question-worthy words or phrases) so that the entire preprocessing part can be automated as well. 

I believe many people at UIUC are very good at phrase extraction (and unstructured data mining in general); perhaps you might have some ideas on how to do it. We are working on it as well. Would be nice to meet you in person to talk about this someday or even collaborate. 

Closing this issue for now. Let me know if you have further problems with the code!

**Comment by zichaow** [comment]
@kashimotoxiang also, my preprocessing script is based largely on the preprocessing script in DrQA repo. They provide several preprocessing engine, one of which is spacy. See https://github.com/facebookresearch/DrQA/tree/master/drqa/tokenizers and https://github.com/facebookresearch/DrQA/blob/master/drqa/reader/predictor.py, which you may find useful.

**Comment by fan8502** [comment]
Hello, the issue  is really help me a lot!
However I’m wondering that if I want to use my own input, did I just put the (input.txt) file in the path (QG-Net/test/input.for.text/)?
